import { useEffect, useState } from 'react';
import { EmployeeLayout } from './EmployeeLayout';
import { TimeAttendanceService, type TimeReport } from '../../services/api/timeAttendance';
export function MyDailyHours() {
  const [rows, setRows] = useState<TimeReport[]>([]); const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [pin, setPin] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  useEffect(() => { TimeAttendanceService.myDaily(date).then(setRows).catch(() => { setRows([]); setError('Unable to load your hours.'); }); }, [date]);
  const savePin = async (event: React.FormEvent) => { event.preventDefault(); if (!/^\d{4}$/.test(pin)) { setError('PIN must be exactly four digits.'); return; } try { await TimeAttendanceService.setMyPin(pin); setPin(''); setError(''); setMessage('Your clock-in PIN was updated.'); } catch { setMessage(''); setError('Unable to update your PIN.'); } };
  return <EmployeeLayout><main className="p-4 sm:p-6 lg:p-8"><div className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-extrabold text-slate-950">My Daily Hours</h1><p className="mt-1 text-sm text-slate-500">Your clock-in and clock-out records.</p></div><input className="rounded-lg border border-slate-200 px-3 py-2 text-sm" type="date" value={date} onChange={event => setDate(event.target.value)} /></div>{message && <p className="mb-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">{message}</p>}{error && <p className="mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="grid gap-6 lg:grid-cols-[2fr_1fr]"><div className="space-y-3">{rows.map(row => <div className="rounded-xl border border-slate-200 bg-white p-4" key={row.reportId}><div className="font-semibold text-slate-900">{row.date || date}</div><div className="mt-1 text-sm text-slate-600">{new Date(row.checkInTime).toLocaleTimeString()} – {row.checkOutTime ? new Date(row.checkOutTime).toLocaleTimeString() : 'Pending checkout'} · {row.timeWorked || '—'}</div></div>)}{!rows.length && <p className="rounded-xl border border-slate-200 bg-white p-5 text-sm text-slate-500">No hours recorded for this date.</p>}</div><form onSubmit={savePin} className="h-fit rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-bold text-slate-900">Reset clock-in PIN</h2><p className="mt-1 text-sm text-slate-500">Use a four-digit PIN for Tap-Time clock-ins.</p><input required inputMode="numeric" maxLength={4} className="mt-4 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" placeholder="4-digit PIN" value={pin} onChange={event => setPin(event.target.value.replace(/\D/g, ''))} /><button className="mt-3 w-full rounded-lg bg-blue-700 px-4 py-2 text-sm font-semibold text-white" type="submit">Update PIN</button></form></div></main></EmployeeLayout>;
}
