import { useEffect, useMemo, useState } from 'react';
import { Plus, Send, Save } from 'lucide-react';
import { SuperAdminLayout } from './SuperAdminLayout';
import { fetchSchools, type School } from '../../services/api/schools';
import { fetchClassrooms, type Classroom } from '../../services/api/admin';
import { createNewsletter, fetchNewsletters, publishNewsletter, renderNewsletterHtml, type Newsletter, type NewsletterBlock } from '../../services/api/newsletters';
const starter: NewsletterBlock[] = [{ type: 'header', title: 'The Goddard School News', body: 'School newsletter' }, { type: 'text', title: 'Welcome', body: 'Add your school update here.' }, { type: 'footer', body: 'The Goddard School' }];
export function SuperAdminNewsPad() { const [schools,setSchools]=useState<School[]>([]),[classes,setClasses]=useState<Classroom[]>([]),[schoolId,setSchoolId]=useState(''),[items,setItems]=useState<Newsletter[]>([]),[title,setTitle]=useState(''),[blocks,setBlocks]=useState<NewsletterBlock[]>(starter),[scope,setScope]=useState<'school'|'classrooms'>('school'),[selected,setSelected]=useState<string[]>([]),[scheduledAt,setScheduledAt]=useState(''),[saving,setSaving]=useState(false);
 const html=useMemo(()=>renderNewsletterHtml(blocks),[blocks]); const load=async(id=schoolId)=>{if(id)setItems((await fetchNewsletters({schoolId:id})).items)}; useEffect(()=>{fetchSchools().then(setSchools)},[]); useEffect(()=>{if(!schoolId)return; fetchClassrooms(schoolId).then(setClasses);load(schoolId)},[schoolId]);
 const save=async(publish=false)=>{if(!schoolId||!title.trim())return;setSaving(true);try{const n=await createNewsletter({schoolId,title,blocks,html,audienceScope:scope,classroomIds:scope==='classrooms'?selected:[]});if(publish)await publishNewsletter(n.id,scheduledAt?new Date(scheduledAt).toISOString():undefined,undefined,[15,7,3]);await load();setTitle('');setBlocks(starter)}finally{setSaving(false)}};
 return <SuperAdminLayout><div className="p-5 lg:p-8 space-y-6"><div><p className="text-xs font-bold tracking-widest uppercase text-blue-600">Communications</p><h1 className="text-3xl font-bold text-slate-900">News Pad</h1></div><div className="grid xl:grid-cols-2 gap-6"><section className="rounded-2xl border bg-white p-5 space-y-4"><select value={schoolId} onChange={e=>setSchoolId(e.target.value)} className="w-full border rounded-xl p-2"><option value="">Select school</option>{schools.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Newsletter title" className="w-full border rounded-xl p-2"/><textarea value={blocks[1]?.body || ''} onChange={e=>setBlocks(b=>b.map((x,i)=>i===1?{...x,body:e.target.value}:x))} rows={8} className="w-full border rounded-xl p-3" placeholder="Newsletter content"/><div className="flex gap-3 text-sm"><label><input type="radio" checked={scope==='school'} onChange={()=>setScope('school')}/> Entire school</label><label><input type="radio" checked={scope==='classrooms'} onChange={()=>setScope('classrooms')}/> Specific classes</label></div>{scope==='classrooms'&&<div className="grid grid-cols-2 gap-2">{classes.map(c=><label key={c.id} className="text-sm"><input type="checkbox" checked={selected.includes(c.id)} onChange={()=>setSelected(v=>v.includes(c.id)?v.filter(id=>id!==c.id):[...v,c.id])}/> {c.name}</label>)}</div>}<label className="block text-sm">Publish date/time (optional)<input type="datetime-local" value={scheduledAt} onChange={e=>setScheduledAt(e.target.value)} className="w-full border rounded-xl p-2 mt-1"/></label><div className="flex gap-2"><button disabled={saving} onClick={()=>save(false)} className="px-4 py-2 rounded-xl border font-semibold"><Save className="w-4 h-4 inline mr-1"/>Save draft</button><button disabled={saving} onClick={()=>save(true)} className="px-4 py-2 rounded-xl bg-[#0F2D52] text-white font-semibold"><Send className="w-4 h-4 inline mr-1"/>{scheduledAt?'Schedule':'Publish'}</button></div></section><section className="rounded-2xl border bg-slate-100 overflow-hidden"><iframe title="Newsletter preview" sandbox="allow-popups" srcDoc={html} className="w-full min-h-[650px] bg-white"/></section></div>{schoolId&&<section className="rounded-2xl border bg-white p-5"><h2 className="font-bold text-lg mb-3">Recent newsletters</h2>{items.map(n=><div key={n.id} className="py-2 border-t flex justify-between"><span>{n.title}</span><span className="text-sm text-slate-500">{n.status}</span></div>)}</section>}</div></SuperAdminLayout> }
