import React, { useEffect, useMemo, useState } from 'react';
import { AdminLayout } from './AdminLayout';
import { TapTimeService } from '../../services/api/tapTime';
import { Loading } from '../../components/ui/loading';
import { Button } from '../../components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '../../components/ui/dialog';
import { CalendarDays, Check, ChevronDown, Edit, Grid2X2, List, Mail, Plus, Search, Settings2, Trash2 } from 'lucide-react';

const frequencies = ['Daily', 'Weekly', 'Biweekly', 'Monthly', 'Bimonthly'];
const viewFrequencies = frequencies.filter(value => value !== 'Daily');
const flags: Record<string, string> = { Daily: 'is_daily_report_active', Weekly: 'is_weekly_report_active', Biweekly: 'is_bi_weekly_report_active', Monthly: 'is_monthly_report_active', Bimonthly: 'is_bi_monthly_report_active' };
const selected = (item: any) => frequencies.filter(value => item[flags[value]]);

export function ReportSettings() {
  const [items, setItems] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [query, setQuery] = useState(''); const [view, setView] = useState<'table' | 'grid'>('table'); const [sortAsc, setSortAsc] = useState(true); const [sortOpen, setSortOpen] = useState(false);
  const [modal, setModal] = useState<'add' | 'edit' | 'delete' | 'view' | null>(null); const [editing, setEditing] = useState<any>(null); const [email, setEmail] = useState(''); const [chosen, setChosen] = useState<string[]>([]); const [viewFrequency, setViewFrequency] = useState(''); const [saving, setSaving] = useState(false);
  const load = async () => { setLoading(true); setError(''); try { const [recipients, frequency] = await Promise.all([TapTimeService.recipients(), TapTimeService.viewFrequency().catch(() => ({ frequency: '' }))]); setItems(recipients.items); setViewFrequency(frequency.frequency || ''); } catch (e: any) { setError(e.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const rows = useMemo(() => items.filter(item => item.company_reporter_email.toLowerCase().includes(query.toLowerCase()) || selected(item).join(' ').toLowerCase().includes(query.toLowerCase())).sort((a, b) => (sortAsc ? 1 : -1) * a.company_reporter_email.localeCompare(b.company_reporter_email)), [items, query, sortAsc]);
  const open = (kind: 'add' | 'edit' | 'delete' | 'view', item?: any) => { setModal(kind); setEditing(item || null); setEmail(item?.company_reporter_email || ''); setChosen(item ? selected(item) : []); };
  const toggle = (value: string) => setChosen(current => current.includes(value) ? current.filter(x => x !== value) : current.length < 2 ? [...current, value] : current);
  const save = async () => { if (!email || !chosen.length) return; setSaving(true); try { if (modal === 'add') await TapTimeService.createRecipient({ email, frequencies: chosen }); else await TapTimeService.updateRecipient(editing.company_reporter_email, { email, frequencies: chosen }); setModal(null); await load(); } catch (e: any) { setError(e.message); } finally { setSaving(false); } };
  const remove = async () => { setSaving(true); try { await TapTimeService.deleteRecipient(editing.company_reporter_email); setModal(null); await load(); } catch (e: any) { setError(e.message); } finally { setSaving(false); } };
  const saveView = async () => { if (!viewFrequency) return; setSaving(true); try { await TapTimeService.updateViewFrequency(viewFrequency); setModal(null); } catch (e: any) { setError(e.message); } finally { setSaving(false); } };
  const editor = modal === 'add' || modal === 'edit';
  return <AdminLayout><main className="min-h-full bg-[#f6f9fd] p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl">
    <header className="flex flex-col gap-4 border-b border-slate-200 pb-6 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="flex items-center gap-2 text-2xl font-bold text-[#0F2D52]"><Settings2 className="h-6 w-6" />Report Settings</h1><p className="mt-1 text-sm text-slate-600">Configure email notifications and report frequencies</p></div><Button className="bg-[#0F2D52] text-white hover:bg-[#173d69] hover:text-white" onClick={() => open('add')}><Plus className="mr-2 h-4 w-4" />Add Setting</Button></header>
    <div className="mt-6 flex flex-col gap-4 sm:flex-row sm:items-center"><div className="relative max-w-md flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-500"/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search email settings..." className="h-10 w-full rounded-lg border border-slate-200 bg-white pl-10 pr-3 text-sm outline-none focus:border-[#1a6fc4]"/></div><div className="relative"><Button variant="outline" onClick={() => setSortOpen(!sortOpen)}><span className="text-emerald-600">↑</span><span className="ml-2">Sort</span><ChevronDown className="ml-8 h-4 w-4"/></Button>{sortOpen && <div className="absolute z-20 mt-1 w-48 rounded-lg border bg-white p-1 shadow-lg"><button className="w-full rounded p-2 text-left text-sm hover:bg-slate-50" onClick={() => { setSortAsc(true); setSortOpen(false); }}>Email: A–Z</button><button className="w-full rounded p-2 text-left text-sm hover:bg-slate-50" onClick={() => { setSortAsc(false); setSortOpen(false); }}>Email: Z–A</button></div>}</div><div className="flex rounded-lg border bg-white p-1"><Button size="sm" variant={view === 'table' ? 'default' : 'ghost'} className={view === 'table' ? 'bg-[#0F2D52] text-white hover:bg-[#173d69] hover:text-white' : ''} onClick={() => setView('table')}><List className="h-4 w-4"/></Button><Button size="sm" variant={view === 'grid' ? 'default' : 'ghost'} className={view === 'grid' ? 'bg-[#0F2D52] text-white hover:bg-[#173d69] hover:text-white' : ''} onClick={() => setView('grid')}><Grid2X2 className="h-4 w-4"/></Button></div></div>
    {loading ? <div className="py-20"><Loading size="md" message="Loading report settings…"/></div> : <>{error && <p className="mt-8 text-red-600">{error}</p>}<section className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 text-lg font-bold text-[#0F2D52]"><Mail className="h-5 w-5"/>Email Report Settings</h2><p className="mt-1 text-sm text-slate-600">Configure email addresses and their report frequencies</p>{rows.length === 0 ? <div className="py-14 text-center text-slate-500">No email settings found.</div> : view === 'grid' ? <div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{rows.map(item => <RecipientCard key={item.company_reporter_email} item={item} onEdit={() => open('edit', item)} onDelete={() => open('delete', item)}/>)}</div> : <div className="mt-5 overflow-x-auto"><table className="w-full border text-sm"><thead className="bg-[#0F2D52] text-white"><tr><th className="p-3">Email Address</th><th className="p-3">Frequency</th><th className="p-3">Actions</th></tr></thead><tbody>{rows.map(item => <tr key={item.company_reporter_email} className="border-b text-center"><td className="p-3 font-medium text-[#0F2D52]">{item.company_reporter_email}</td><td className="p-3"><Chips values={selected(item)}/></td><td className="p-3"><button className="mr-4 text-[#0F2D52]" onClick={() => open('edit', item)}><Edit className="h-4 w-4"/></button><button className="text-red-500" onClick={() => open('delete', item)}><Trash2 className="h-4 w-4"/></button></td></tr>)}</tbody></table></div>}</section><section className="mt-8 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 text-lg font-bold text-[#0F2D52]"><CalendarDays className="h-5 w-5"/>Email Consolidated Report Settings</h2><p className="mt-1 text-sm text-slate-600">Configure the default report viewing frequency</p><div className="mt-5 overflow-x-auto"><table className="w-full border text-sm"><thead className="bg-[#0F2D52] text-white"><tr><th className="p-3">Current Frequency</th><th className="p-3">Actions</th></tr></thead><tbody><tr className="text-center"><td className="p-4">{viewFrequency ? <span className="rounded-full bg-emerald-100 px-3 py-1 text-emerald-800">{viewFrequency}</span> : 'Not configured'}</td><td><button className="text-[#0F2D52]" onClick={() => open('view')}><Edit className="h-4 w-4"/></button></td></tr></tbody></table></div></section></>}
  </div></main><Dialog open={!!modal} onOpenChange={() => !saving && setModal(null)}><DialogContent className="sm:max-w-md"><DialogHeader><DialogTitle className="flex items-center gap-2 text-[#0F2D52]">{editor ? <Edit className="h-5 w-5"/> : modal === 'view' ? <CalendarDays className="h-5 w-5"/> : <Trash2 className="h-5 w-5"/>}{modal === 'add' ? 'Add Email Setting' : modal === 'edit' ? 'Edit Email Setting' : modal === 'view' ? 'Edit View Settings' : 'Delete Email Setting'}</DialogTitle><DialogDescription>{editor ? 'Configure email notification settings' : modal === 'view' ? 'Configure default report viewing frequency' : `Delete the setting for ${editing?.company_reporter_email}?`}</DialogDescription></DialogHeader>{editor && <div className="space-y-4"><label className="grid gap-2 text-sm font-medium">Email Address *<input value={email} onChange={e => setEmail(e.target.value)} type="email" className="h-10 rounded-md border px-3"/></label><FrequencyButtons values={chosen} toggle={toggle}/></div>}{modal === 'view' && <div className="grid grid-cols-2 gap-2">{viewFrequencies.map(value => <Button key={value} variant={viewFrequency === value ? 'default' : 'outline'} className={viewFrequency === value ? 'bg-[#0F2D52] text-white hover:bg-[#173d69] hover:text-white' : ''} onClick={() => setViewFrequency(value)}>{value}</Button>)}</div>}<DialogFooter><Button variant="outline" onClick={() => setModal(null)}>Cancel</Button><Button className="bg-[#0F2D52] text-white hover:bg-[#173d69] hover:text-white" disabled={saving || (editor && (!email || !chosen.length))} onClick={modal === 'delete' ? remove : modal === 'view' ? saveView : save}>{saving ? 'Saving…' : modal === 'delete' ? 'Delete Setting' : modal === 'view' ? 'Update Settings' : modal === 'edit' ? 'Update Setting' : 'Save Setting'}</Button></DialogFooter></DialogContent></Dialog></AdminLayout>;
}
function Chips({ values }: { values: string[] }) { return <div className="flex flex-wrap justify-center gap-2">{values.map(value => <span key={value} className="rounded-full bg-blue-100 px-2.5 py-1 text-xs text-blue-800">{value}</span>)}</div>; }
function RecipientCard({ item, onEdit, onDelete }: { item: any; onEdit: () => void; onDelete: () => void }) { return <div className="rounded-xl border p-4"><div className="flex items-start justify-between"><div><p className="font-semibold text-[#0F2D52]">{item.company_reporter_email}</p><p className="mt-2"><Chips values={selected(item)}/></p></div><div className="flex gap-2"><button className="text-[#0F2D52]" onClick={onEdit}><Edit className="h-4 w-4"/></button><button className="text-red-500" onClick={onDelete}><Trash2 className="h-4 w-4"/></button></div></div></div>; }
function FrequencyButtons({ values, toggle }: { values: string[]; toggle: (value: string) => void }) { return <div><p className="mb-2 text-sm font-medium">Report Frequency * (Max 2)</p><div className="grid grid-cols-2 gap-2">{frequencies.map(value => <Button key={value} variant={values.includes(value) ? 'default' : 'outline'} className={values.includes(value) ? 'bg-[#0F2D52] text-white hover:bg-[#173d69] hover:text-white' : ''} disabled={!values.includes(value) && values.length >= 2} onClick={() => toggle(value)}>{values.includes(value) && <Check className="mr-1 h-3 w-3"/>}{value}</Button>)}</div></div>; }
