import React, { useEffect, useMemo, useState } from 'react';
import { AdminLayout } from './AdminLayout';
import { TapTimeService } from '../../services/api/tapTime';
import { Loading } from '../../components/ui/loading';
import { Button } from '../../components/ui/button';
import { Input } from '../../components/ui/input';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '../../components/ui/dialog';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '../../components/ui/dropdown-menu';
import { CalendarDays, Check, ChevronDown, Edit, Grid2X2, List, Plus, Search, Settings2, Trash2 } from 'lucide-react';

const frequencies = ['Daily', 'Weekly', 'Biweekly', 'Monthly', 'Bimonthly'];
const viewFrequencies = frequencies.filter(value => value !== 'Daily');
const flags: Record<string, string> = { Daily: 'is_daily_report_active', Weekly: 'is_weekly_report_active', Biweekly: 'is_bi_weekly_report_active', Monthly: 'is_monthly_report_active', Bimonthly: 'is_bi_monthly_report_active' };
const selected = (item: any) => frequencies.filter(value => item[flags[value]]);
const primaryButton = 'bg-gradient-to-br from-[#0F2D52] to-[#1E4B83] text-white hover:opacity-95 hover:text-white border-none shadow-xs';

export function ReportSettings() {
  const [items, setItems] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [query, setQuery] = useState(''); const [view, setView] = useState<'table' | 'grid'>('table'); const [sortAsc, setSortAsc] = useState(true);
  const [modal, setModal] = useState<'add' | 'edit' | 'delete' | 'view' | null>(null); const [editing, setEditing] = useState<any>(null); const [email, setEmail] = useState(''); const [chosen, setChosen] = useState<string[]>([]); const [viewFrequency, setViewFrequency] = useState(''); const [saving, setSaving] = useState(false);
  const load = async () => { setLoading(true); setError(''); try { const [recipients, frequency] = await Promise.all([TapTimeService.recipients(), TapTimeService.viewFrequency().catch(() => ({ frequency: '' }))]); setItems(recipients.items); setViewFrequency(frequency.frequency || ''); } catch (e: any) { setError(e.message); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const rows = useMemo(() => items.filter(item => item.company_reporter_email.toLowerCase().includes(query.toLowerCase()) || selected(item).join(' ').toLowerCase().includes(query.toLowerCase())).sort((a, b) => (sortAsc ? 1 : -1) * a.company_reporter_email.localeCompare(b.company_reporter_email)), [items, query, sortAsc]);
  const open = (kind: 'add' | 'edit' | 'delete' | 'view', item?: any) => { setModal(kind); setEditing(item || null); setEmail(item?.company_reporter_email || ''); setChosen(item ? selected(item) : []); };
  const toggle = (value: string) => setChosen(current => current.includes(value) ? current.filter(x => x !== value) : current.length < 2 ? [...current, value] : current);
  const save = async () => { if (!email || !chosen.length) return; setSaving(true); try { if (modal === 'add') await TapTimeService.createRecipient({ email, frequencies: chosen }); else await TapTimeService.updateRecipient(editing.company_reporter_email, { email, frequencies: chosen }); setModal(null); await load(); } catch (e: any) { setError(e.message); } finally { setSaving(false); } };
  const remove = async () => { setSaving(true); try { await TapTimeService.deleteRecipient(editing.company_reporter_email); setModal(null); await load(); } catch (e: any) { setError(e.message); } finally { setSaving(false); } };
  const saveView = async () => { if (!viewFrequency) return; setSaving(true); try { await TapTimeService.updateViewFrequency(viewFrequency); setModal(null); } catch (e: any) { setError(e.message); } finally { setSaving(false); } };
  const editor = modal === 'add' || modal === 'edit';

  return <AdminLayout><main className="min-h-full bg-[#f6f9fd] p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl space-y-6">
    <header className="flex flex-col justify-between gap-4 rounded-2xl border border-slate-100 bg-white p-5 shadow-xs sm:flex-row sm:items-center sm:p-6"><div><h1 className="flex items-center gap-2 text-xl font-extrabold tracking-tight text-slate-900 sm:text-2xl"><Settings2 className="h-5 w-5 text-[#0F2D52]" />Report Settings</h1><p className="mt-1 text-xs font-semibold text-slate-400 sm:text-sm">Configure email notifications and report frequencies</p></div><Button className={primaryButton} onClick={() => open('add')}><Plus className="mr-2 h-4 w-4" />Add Setting</Button></header>
    <section className="overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-sm"><div className="border-b border-slate-100 bg-slate-50/50 px-5 py-4"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="text-sm font-bold text-slate-900">Email Report Settings</h2><p className="mt-0.5 text-xs font-semibold text-slate-400">{rows.length} configured recipient{rows.length === 1 ? '' : 's'}</p></div><div className="flex items-center gap-2"><DropdownMenu><DropdownMenuTrigger asChild><Button size="sm" variant="outline"><span className="text-[#0F2D52]">{sortAsc ? '↑' : '↓'}</span><span className="ml-1.5">Sort</span><ChevronDown className="ml-3 h-3.5 w-3.5 text-slate-400" /></Button></DropdownMenuTrigger><DropdownMenuContent align="end" className="rounded-xl border-slate-100 shadow-xl"><DropdownMenuItem className="cursor-pointer text-xs" onClick={() => setSortAsc(true)}>Email: A–Z</DropdownMenuItem><DropdownMenuItem className="cursor-pointer text-xs" onClick={() => setSortAsc(false)}>Email: Z–A</DropdownMenuItem></DropdownMenuContent></DropdownMenu><ViewToggle value={view} onChange={setView} /></div></div><div className="relative mt-4"><Search className={`absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 ${query ? 'text-[#0F2D52]' : 'text-slate-400'}`} /><Input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search email settings..." className="pl-9" /></div></div>
      {loading ? <div className="py-20"><Loading size="md" message="Loading report settings…" /></div> : <>{error && <p className="m-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}{rows.length === 0 ? <div className="py-14 text-center text-sm text-slate-400">No email settings found.</div> : view === 'grid' ? <div className="grid gap-5 p-5 sm:grid-cols-2 lg:grid-cols-3">{rows.map(item => <RecipientCard key={item.company_reporter_email} item={item} onEdit={() => open('edit', item)} onDelete={() => open('delete', item)} />)}</div> : <RecipientTable rows={rows} onEdit={item => open('edit', item)} onDelete={item => open('delete', item)} />}</>}
    </section>
    <section className="overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-sm"><div className="border-b border-slate-100 bg-slate-50/50 px-5 py-4"><h2 className="flex items-center gap-2 text-sm font-bold text-slate-900"><CalendarDays className="h-4 w-4 text-[#0F2D52]" />Email Consolidated Report Settings</h2><p className="mt-0.5 text-xs font-semibold text-slate-400">Configure the default report viewing frequency</p></div><div className="overflow-x-auto"><table className="w-full min-w-[520px] text-sm"><thead className="bg-slate-50/80"><tr><th className="border-y border-slate-200/85 px-5 py-3.5 text-left text-xs font-bold uppercase tracking-wider text-slate-500">Current Frequency</th><th className="border-y border-slate-200/85 px-5 py-3.5 text-right text-xs font-bold uppercase tracking-wider text-slate-500">Actions</th></tr></thead><tbody><tr className="border-b border-slate-50 hover:bg-[#F8FAFC]"><td className="px-5 py-4">{viewFrequency ? <span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-700">{viewFrequency}</span> : <span className="text-sm text-slate-400">Not configured</span>}</td><td className="px-5 py-4 text-right"><Button size="sm" variant="outline" onClick={() => open('view')}><Edit className="mr-1.5 h-3.5 w-3.5" />Edit</Button></td></tr></tbody></table></div></section>
  </div></main><Dialog open={!!modal} onOpenChange={() => !saving && setModal(null)}><DialogContent className="sm:max-w-md"><DialogHeader><DialogTitle className="flex items-center gap-2">{editor ? <Edit className="h-5 w-5 text-[#0F2D52]" /> : modal === 'view' ? <CalendarDays className="h-5 w-5 text-[#0F2D52]" /> : <Trash2 className="h-5 w-5 text-red-500" />}{modal === 'add' ? 'Add Email Setting' : modal === 'edit' ? 'Edit Email Setting' : modal === 'view' ? 'Edit View Settings' : 'Delete Email Setting'}</DialogTitle><DialogDescription>{editor ? 'Configure email notification settings.' : modal === 'view' ? 'Configure default report viewing frequency.' : `Delete the setting for ${editing?.company_reporter_email}?`}</DialogDescription></DialogHeader>{editor && <div className="space-y-5"><label className="grid gap-1.5 text-xs font-bold uppercase tracking-wider text-slate-500">Email Address *<Input value={email} onChange={e => setEmail(e.target.value)} type="email" /></label><FrequencyButtons values={chosen} toggle={toggle} /></div>}{modal === 'view' && <div className="grid grid-cols-2 gap-2">{viewFrequencies.map(value => <Button key={value} variant={viewFrequency === value ? 'default' : 'outline'} className={viewFrequency === value ? primaryButton : ''} onClick={() => setViewFrequency(value)}>{value}</Button>)}</div>}<DialogFooter><Button variant="outline" onClick={() => setModal(null)} disabled={saving}>Cancel</Button><Button className={modal === 'delete' ? 'bg-red-500 text-white hover:bg-red-600 hover:text-white' : primaryButton} disabled={saving || (editor && (!email || !chosen.length))} onClick={modal === 'delete' ? remove : modal === 'view' ? saveView : save}>{saving ? 'Saving…' : modal === 'delete' ? 'Delete Setting' : modal === 'view' ? 'Update Settings' : modal === 'edit' ? 'Update Setting' : 'Save Setting'}</Button></DialogFooter></DialogContent></Dialog></AdminLayout>;
}

function ViewToggle({ value, onChange }: { value: 'table' | 'grid'; onChange: (value: 'table' | 'grid') => void }) { return <div className="flex items-center gap-1 rounded-xl border border-slate-200/50 bg-slate-100/80 p-1"><button type="button" onClick={() => onChange('table')} className={`flex items-center gap-1 rounded-lg px-3 py-2 text-xs font-bold ${value === 'table' ? 'bg-white text-[#0F2D52] shadow-xs' : 'text-slate-500 hover:text-slate-800'}`}><List className="h-3.5 w-3.5" />Table</button><button type="button" onClick={() => onChange('grid')} className={`flex items-center gap-1 rounded-lg px-3 py-2 text-xs font-bold ${value === 'grid' ? 'bg-white text-[#0F2D52] shadow-xs' : 'text-slate-500 hover:text-slate-800'}`}><Grid2X2 className="h-3.5 w-3.5" />Cards</button></div>; }
function Chips({ values }: { values: string[] }) { return <div className="flex flex-wrap gap-2">{values.map(value => <span key={value} className="rounded-full bg-[#EFF5FB] px-2.5 py-1 text-xs font-bold text-[#0F2D52]">{value}</span>)}</div>; }
function RecipientTable({ rows, onEdit, onDelete }: { rows: any[]; onEdit: (item: any) => void; onDelete: (item: any) => void }) { return <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-sm"><thead className="bg-slate-50/80"><tr>{['Email Address', 'Frequency', 'Actions'].map((header, index) => <th key={header} className={`border-y border-slate-200/85 px-5 py-3.5 text-left text-xs font-bold uppercase tracking-wider text-slate-500 ${index === 2 ? 'text-right' : ''}`}>{header}</th>)}</tr></thead><tbody>{rows.map(item => <tr key={item.company_reporter_email} className="border-b border-slate-50 transition-colors hover:bg-[#F8FAFC]"><td className="px-5 py-4 font-bold text-[#0F2D52]">{item.company_reporter_email}</td><td className="px-5 py-4"><Chips values={selected(item)} /></td><td className="px-5 py-4 text-right"><div className="inline-flex gap-2"><Button size="icon" variant="ghost" className="h-8 w-8" aria-label="Edit email setting" onClick={() => onEdit(item)}><Edit className="h-4 w-4" /></Button><Button size="icon" variant="ghost" className="h-8 w-8 text-red-500 hover:bg-red-50 hover:text-red-600" aria-label="Delete email setting" onClick={() => onDelete(item)}><Trash2 className="h-4 w-4" /></Button></div></td></tr>)}</tbody></table></div>; }
function RecipientCard({ item, onEdit, onDelete }: { item: any; onEdit: () => void; onDelete: () => void }) { return <div className="rounded-2xl border border-slate-100 bg-white p-5 shadow-xs transition-all hover:shadow-md"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate font-bold text-[#0F2D52]">{item.company_reporter_email}</p><div className="mt-3"><Chips values={selected(item)} /></div></div><div className="flex gap-1"><Button size="icon" variant="ghost" className="h-8 w-8" aria-label="Edit email setting" onClick={onEdit}><Edit className="h-4 w-4" /></Button><Button size="icon" variant="ghost" className="h-8 w-8 text-red-500 hover:bg-red-50 hover:text-red-600" aria-label="Delete email setting" onClick={onDelete}><Trash2 className="h-4 w-4" /></Button></div></div></div>; }
function FrequencyButtons({ values, toggle }: { values: string[]; toggle: (value: string) => void }) { return <div><p className="mb-2 text-xs font-bold uppercase tracking-wider text-slate-500">Report Frequency * (Max 2)</p><div className="grid grid-cols-2 gap-2">{frequencies.map(value => <Button key={value} variant={values.includes(value) ? 'default' : 'outline'} className={values.includes(value) ? primaryButton : ''} disabled={!values.includes(value) && values.length >= 2} onClick={() => toggle(value)}>{values.includes(value) && <Check className="mr-1 h-3 w-3" />}{value}</Button>)}</div></div>; }
